<?php

// Defined all system routes (Main Frontend, Games, Agent Portal, Affiliate Portal, Admin Console)

$routes = [
    '/' => 'default',
    '/status' => 'status', 
    '/home' => 'admin/index.php',
    '/route-app-status' => 'route-paths/request-app-status.php',
    '/route-agent-affiliate-status' => 'route-paths/request-agent-affiliate-status.php',
    '/route-send-sms' => 'route-paths/services/sms/send-sms.php',
    '/route-login' => 'route-paths/request-login.php',
    '/route-create-account' => 'route-paths/request-create-account.php',
    '/route-change-password' => 'route-paths/request-change-password.php',
    '/route-reset-password' => 'route-paths/request-reset-password.php',
    '/route-claim-giftcard' => 'route-paths/request-claim-giftcard.php',
    
    '/route-account-info' => 'route-paths/request-account-info.php',
    '/route-allmember-records' => 'route-paths/load-all-members.php',
    '/route-devicemanager-records' => 'route-paths/load-devicemanager.php',
    '/route-recharge-request' => 'route-paths/request-recharge.php',
    '/route-recharge-records' => 'route-paths/load-recharge-records.php',
    '/route-transactions' => 'route-paths/load-transactions.php',
    '/route-team-reports' => 'route-paths/load-team-reports.php',
    
    '/route-withdraw-request' => 'route-paths/request-withdrawl.php',
    '/route-withdraw-records' => 'route-paths/load-withdraw-records.php',
    
    '/route-get-banklist' => 'route-paths/load-bank-list.json',
    '/route-deposit-info' => 'route-paths/load-deposit-details.php',
    '/route-get-bankcards' => 'route-paths/load-bank-cards.php',
    '/route-add-bankcard' => 'route-paths/request-add-bankcard.php',
    '/route-delete-bankcard' => 'route-paths/request-delete-bankcard.php',
    '/route-set-bankcard-primary' => 'route-paths/set-bankcard-primary.php',
    '/route-get-primary-bankcard' => 'route-paths/load-primary-bankcard.php',
    
    '/route-play-games' => 'route-paths/request-play-games.php',
    '/route-mygame-records' => 'route-paths/load-mygame-records.php',
    '/route-game-notifications' => 'route-paths/load-game-notifications.php',
    '/route-submit-ticket' => 'route-paths/request-submit-ticket.php',
    '/route-active-promotions' => 'route-paths/request-active-promotions.php',
    '/request-bonus-details' => 'route-paths/request-bonus-details.php',
    '/request-claim-bonus' => 'route-paths/request-claim-bonus.php',
    '/route-claim-cashback' => 'route-paths/request-claim-cashback.php',
    '/request-cancel-bonus' => 'route-paths/request-cancel-bonus.php',
    '/route-active-bonus-details' => 'route-paths/request-active-bonus-details.php',
    '/route-offer-promotions' => 'route-paths/request-offers.php',
    '/route-trending-matches' => 'route-paths/load-trending-matches.php',
    '/route-big-wins' => 'route-paths/load-big-wins.php',
    '/route-get-user-tickets' => 'route-paths/load-user-tickets.php',
    '/route-get-games' => 'route-paths/request-get-games.php',
    '/route-get-broadcasts' => 'route-paths/request-get-broadcasts.php',
    '/route-mark-broadcast-seen' => 'route-paths/request-mark-broadcast-seen.php',
    '/route-payment-methods' => 'route-paths/get-payment-methods.php',
    '/route-get-payment-methods' => 'route-paths/get-payment-methods.php',
    '/game' => 'game/index.php',

    '/india-lotto-callback/get_point' => 'route-paths/callbacks/india-lotto-get-point.php',
    '/india-lotto-callback/change_point' => 'route-paths/callbacks/india-lotto-change-point.php',
    '/proxy.php' => 'proxy.php',
    '/proxy' => 'proxy.php',

    // ==========================================
    // AGENT PORTAL API ROUTES (/agent/* & /api/v1/agent/*)
    // ==========================================
    '/agent/auth/login' => 'agent/auth/login.php',
    '/api/v1/agent/auth/login' => 'agent/auth/login.php',
    '/agent/auth/apply' => 'agent/auth/apply.php',
    '/api/v1/agent/auth/apply' => 'agent/auth/apply.php',
    '/api/v1/agent/apply' => 'agent/auth/apply.php',
    '/api/v1/agent/auth/apply_status' => 'agent/auth/apply_status.php',
    '/agent/auth/2fa/setup' => 'agent/auth/setup_2fa.php',
    '/api/v1/agent/auth/2fa/setup' => 'agent/auth/setup_2fa.php',
    '/agent/auth/2fa/enable' => 'agent/auth/enable_2fa.php',
    '/api/v1/agent/auth/2fa/enable' => 'agent/auth/enable_2fa.php',
    '/agent/auth/2fa/verify' => 'agent/auth/verify_2fa.php',
    '/api/v1/agent/auth/2fa/verify' => 'agent/auth/verify_2fa.php',
    '/agent/dashboard' => 'agent/dashboard/index.php',
    '/api/v1/agent/dashboard' => 'agent/dashboard/index.php',
    '/agent/downlines' => 'agent/downlines/index.php',
    '/api/v1/agent/downlines' => 'agent/downlines/index.php',
    '/agent/downlines/create' => 'agent/downlines/create.php',
    '/api/v1/agent/downlines/create' => 'agent/downlines/create.php',
    '/agent/credit/transfer' => 'agent/credit/transfer.php',
    '/api/v1/agent/credit/transfer' => 'agent/credit/transfer.php',
    '/agent/credit/statement' => 'agent/credit/statement.php',
    '/api/v1/agent/credit/statement' => 'agent/credit/statement.php',
    '/agent/reports/pnl' => 'agent/reports/pnl.php',
    '/api/v1/agent/reports/pnl' => 'agent/reports/pnl.php',
    '/agent/reports/exposure' => 'agent/reports/exposure.php',
    '/api/v1/agent/reports/exposure' => 'agent/reports/exposure.php',
    '/agent/reports/bet-list' => 'agent/reports/bet_list.php',
    '/api/v1/agent/reports/bet-list' => 'agent/reports/bet_list.php',
    '/agent/reports/pl-agent' => 'agent/reports/pl_agent.php',
    '/api/v1/agent/reports/pl-agent' => 'agent/reports/pl_agent.php',
    '/agent/reports/pl-event' => 'agent/reports/pl_event.php',
    '/api/v1/agent/reports/pl-event' => 'agent/reports/pl_event.php',
    '/agent/reports/pl-market' => 'agent/reports/pl_market.php',
    '/api/v1/agent/reports/pl-market' => 'agent/reports/pl_market.php',
    '/agent/reports/real-revenue' => 'agent/reports/real_revenue.php',
    '/api/v1/agent/reports/real-revenue' => 'agent/reports/real_revenue.php',
    '/agent/reports/settlement' => 'agent/reports/settlement.php',
    '/api/v1/agent/reports/settlement' => 'agent/reports/settlement.php',
    '/agent/reports/transactions' => 'agent/reports/transactions.php',
    '/api/v1/agent/reports/transactions' => 'agent/reports/transactions.php',
    '/agent/reports/transfer-statement' => 'agent/reports/transfer_statement.php',
    '/api/v1/agent/reports/transfer-statement' => 'agent/reports/transfer_statement.php',
    '/agent/analysis/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/api/v1/agent/analysis/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/agent/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/api/v1/agent/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/agent/profile' => 'agent/profile/index.php',
    '/api/v1/agent/profile' => 'agent/profile/index.php',
    '/agent/players' => 'agent/players/index.php',
    '/api/v1/agent/players' => 'agent/players/index.php',

    // AGENT APPROVAL ENGINE ROUTES
    '/agent/approvals' => 'agent/approvals/index.php',
    '/api/v1/agent/approvals' => 'agent/approvals/index.php',
    '/agent/approvals/action' => 'agent/approvals/action.php',
    '/api/v1/agent/approvals/action' => 'agent/approvals/action.php',
    '/agent/approvals/count' => 'agent/approvals/count.php',
    '/api/v1/agent/approvals/count' => 'agent/approvals/count.php',
    '/agent/players/create' => 'agent/players/create.php',
    '/api/v1/agent/players/create' => 'agent/players/create.php',
    '/agent/players/credit' => 'agent/players/credit.php',
    '/api/v1/agent/players/credit' => 'agent/players/credit.php',
    '/agent/payouts/history' => 'agent/payouts/history.php',
    '/api/v1/agent/payouts/history' => 'agent/payouts/history.php',
    '/agent/payouts/request' => 'agent/payouts/request.php',
    '/api/v1/agent/payouts/request' => 'agent/payouts/request.php',
    '/agent/downlines/index.php' => 'agent/downlines/index.php',
    '/agent/downlines/create.php' => 'agent/downlines/create.php',
    '/agent/players/index.php' => 'agent/players/index.php',
    '/agent/players/create.php' => 'agent/players/create.php',
    '/agent/players/credit.php' => 'agent/players/credit.php',
    '/agent/profile/index.php' => 'agent/profile/index.php',
    '/agent/credit/transfer.php' => 'agent/credit/transfer.php',
    '/agent/credit/statement.php' => 'agent/credit/statement.php',

    // ==========================================
    // AFFILIATE PORTAL API ROUTES (/affiliate/* & /api/v1/affiliate/*)
    // ==========================================
    '/affiliate/auth/register' => 'affiliate/auth/register.php',
    '/api/v1/affiliate/auth/register' => 'affiliate/auth/register.php',
    '/affiliate/auth/login' => 'affiliate/auth/login.php',
    '/api/v1/affiliate/auth/login' => 'affiliate/auth/login.php',
    '/affiliate/auth/status' => 'affiliate/auth/status.php',
    '/api/v1/affiliate/auth/status' => 'affiliate/auth/status.php',
    '/affiliate/onboarding/complete' => 'affiliate/onboarding/complete.php',
    '/api/v1/affiliate/onboarding/complete' => 'affiliate/onboarding/complete.php',
    '/affiliate/dashboard' => 'affiliate/dashboard/index.php',
    '/api/v1/affiliate/dashboard' => 'affiliate/dashboard/index.php',
    '/affiliate/links' => 'affiliate/links/index.php',
    '/api/v1/affiliate/links' => 'affiliate/links/index.php',
    '/affiliate/referrals' => 'affiliate/referrals/index.php',
    '/api/v1/affiliate/referrals' => 'affiliate/referrals/index.php',
    '/affiliate/earnings' => 'affiliate/earnings/index.php',
    '/api/v1/affiliate/earnings' => 'affiliate/earnings/index.php',
    '/affiliate/earnings/cycle-metrics' => 'affiliate/earnings/cycle_metrics.php',
    '/api/v1/affiliate/earnings/cycle-metrics' => 'affiliate/earnings/cycle_metrics.php',
    '/affiliate/payouts/request' => 'affiliate/payouts/request.php',
    '/api/v1/affiliate/payouts/request' => 'affiliate/payouts/request.php',
    '/affiliate/payouts/history' => 'affiliate/payouts/history.php',
    '/api/v1/affiliate/payouts/history' => 'affiliate/payouts/history.php',
    '/affiliate/methods' => 'affiliate/methods/index.php',
    '/api/v1/affiliate/methods' => 'affiliate/methods/index.php',
    '/affiliate/kyc' => 'affiliate/kyc/index.php',
    '/api/v1/affiliate/kyc' => 'affiliate/kyc/index.php',
    '/affiliate/kyc/upload' => 'affiliate/kyc/upload.php',
    '/api/v1/affiliate/kyc/upload' => 'affiliate/kyc/upload.php',
    '/affiliate/track' => 'affiliate/links/track.php',
    '/api/v1/affiliate/track' => 'affiliate/links/track.php',
    '/api/v1/affiliate/track/click' => 'affiliate/links/track.php',

    '/affiliate/preferences' => 'affiliate/preferences/index.php',
    '/api/v1/affiliate/preferences' => 'affiliate/preferences/index.php',
    '/affiliate/auth/2fa/setup' => 'affiliate/auth/2fa/setup.php',
    '/api/v1/affiliate/auth/2fa/setup' => 'affiliate/auth/2fa/setup.php',
    '/affiliate/auth/2fa/enable' => 'affiliate/auth/2fa/enable.php',
    '/api/v1/affiliate/auth/2fa/enable' => 'affiliate/auth/2fa/enable.php',
    '/affiliate/auth/2fa/disable' => 'affiliate/auth/2fa/disable.php',
    '/api/v1/affiliate/auth/2fa/disable' => 'affiliate/auth/2fa/disable.php',
    '/affiliate/auth/2fa/verify_login' => 'affiliate/auth/2fa/verify_login.php',
    '/api/v1/affiliate/auth/2fa/verify_login' => 'affiliate/auth/2fa/verify_login.php',
    '/affiliate/settings' => 'affiliate/settings/index.php',
    '/api/v1/affiliate/settings' => 'affiliate/settings/index.php',
    '/affiliate/support' => 'affiliate/support/index.php',
    '/api/v1/affiliate/support' => 'affiliate/support/index.php',
    '/affiliate/notifications' => 'affiliate/notifications/index.php',
    '/api/v1/affiliate/notifications' => 'affiliate/notifications/index.php',
    '/affiliate/network' => 'affiliate/network/index.php',
    '/api/v1/affiliate/network' => 'affiliate/network/index.php',
    '/affiliate/reports' => 'affiliate/reports/index.php',
    '/api/v1/affiliate/reports' => 'affiliate/reports/index.php',
    '/affiliate/player-bets' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/player-bets' => 'affiliate/reports/player_bets.php',
    '/affiliate/test_webhook' => 'affiliate/test_webhook.php',
    '/affiliate/test_webhook.php' => 'affiliate/test_webhook.php',
    '/api/v1/affiliate/test_webhook' => 'affiliate/test_webhook.php',

    // ==========================================
    // ADMIN CONSOLE AGENT & AFFILIATE MANAGEMENT API ROUTES
    // ==========================================
    '/admin/agents/api_list' => 'admin/agents/api_list.php',
    '/api/v1/admin/agents' => 'admin/agents/api_list.php',
    '/admin/agents/detail/api_detail' => 'admin/agents/detail/api_detail.php',
    '/api/v1/admin/agents/detail' => 'admin/agents/detail/api_detail.php',
    '/admin/agents/credit/api_credit' => 'admin/agents/credit/api_credit.php',
    '/api/v1/admin/agents/credit' => 'admin/agents/credit/api_credit.php',
    '/admin/agents/status/api_status' => 'admin/agents/status/api_status.php',
    '/api/v1/admin/agents/status' => 'admin/agents/status/api_status.php',
    '/admin/agents/api_delete' => 'admin/agents/api_delete.php',
    '/api/v1/admin/agents/delete' => 'admin/agents/api_delete.php',
    '/admin/agents/api_password' => 'admin/agents/api_password.php',
    '/api/v1/admin/agents/password' => 'admin/agents/api_password.php',
    '/admin/agents/applications/api_applications' => 'admin/agents/applications/api_applications.php',
    '/api/v1/admin/agents/applications' => 'admin/agents/applications/api_applications.php',
    '/admin/agents/settings/api_settings' => 'admin/agents/settings/api_settings.php',
    '/api/v1/admin/agents/settings' => 'admin/agents/settings/api_settings.php',

    '/admin/affiliates/api_list' => 'admin/affiliates/api_list.php',
    '/api/v1/admin/affiliates' => 'admin/affiliates/api_list.php',
    '/admin/affiliates/api_kyc' => 'admin/affiliates/api_kyc.php',
    '/api/v1/admin/affiliates/kyc' => 'admin/affiliates/api_kyc.php',
    '/admin/affiliates/commissions/run' => 'admin/affiliates/commissions/run/index.php',
    '/api/v1/admin/affiliates/commissions/run' => 'admin/affiliates/commissions/run/index.php',
    '/admin/affiliates/payouts/api_payouts' => 'admin/affiliates/payouts/api_payouts.php',
    '/api/v1/admin/affiliates/payouts' => 'admin/affiliates/payouts/api_payouts.php',
    '/admin/affiliates/settings/api_settings' => 'admin/affiliates/settings/api_settings.php',
    '/api/v1/admin/affiliates/settings' => 'admin/affiliates/settings/api_settings.php',

    // ==========================================
    // AGENT CONSOLE & PORTAL API ROUTES
    // ==========================================
    '/agent/auth/login' => 'agent/auth/login.php',
    '/api/v1/agent/auth/login' => 'agent/auth/login.php',
    '/agent/auth/apply' => 'agent/auth/apply.php',
    '/api/v1/agent/auth/apply' => 'agent/auth/apply.php',
    '/api/v1/agent/apply' => 'agent/auth/apply.php',
    '/agent/auth/apply_status' => 'agent/auth/apply_status.php',
    '/api/v1/agent/auth/apply_status' => 'agent/auth/apply_status.php',
    '/api/v1/agent/apply-status' => 'agent/auth/apply_status.php',
    '/agent/auth/2fa/setup' => 'agent/auth/setup_2fa.php',
    '/api/v1/agent/auth/2fa/setup' => 'agent/auth/setup_2fa.php',
    '/agent/auth/2fa/verify' => 'agent/auth/verify_2fa.php',
    '/api/v1/agent/auth/2fa/verify' => 'agent/auth/verify_2fa.php',
    '/agent/auth/2fa/enable' => 'agent/auth/enable_2fa.php',
    '/api/v1/agent/auth/2fa/enable' => 'agent/auth/enable_2fa.php',

    '/agent/dashboard' => 'agent/dashboard/index.php',
    '/api/v1/agent/dashboard' => 'agent/dashboard/index.php',
    '/agent/downlines' => 'agent/downlines/index.php',
    '/api/v1/agent/downlines' => 'agent/downlines/index.php',
    '/agent/downlines/create' => 'agent/downlines/create.php',
    '/api/v1/agent/downlines/create' => 'agent/downlines/create.php',
    '/agent/players' => 'agent/players/index.php',
    '/api/v1/agent/players' => 'agent/players/index.php',
    '/agent/players/create' => 'agent/players/create.php',
    '/api/v1/agent/players/create' => 'agent/players/create.php',
    '/agent/players/credit' => 'agent/players/credit.php',
    '/api/v1/agent/players/credit' => 'agent/players/credit.php',
    '/agent/players/transfer' => 'agent/players/credit.php',
    '/api/v1/agent/players/transfer' => 'agent/players/credit.php',
    '/agent/players/deposit' => 'agent/players/credit.php',
    '/api/v1/agent/players/deposit' => 'agent/players/credit.php',
    '/agent/profile' => 'agent/profile/index.php',
    '/api/v1/agent/profile' => 'agent/profile/index.php',
    '/agent/credit/transfer' => 'agent/credit/transfer.php',
    '/api/v1/agent/credit/transfer' => 'agent/credit/transfer.php',
    '/agent/credit/statement' => 'agent/credit/statement.php',
    '/api/v1/agent/credit/statement' => 'agent/credit/statement.php',
    '/agent/payouts/request' => 'agent/payouts/request.php',
    '/api/v1/agent/payouts/request' => 'agent/payouts/request.php',
    '/agent/payouts/history' => 'agent/payouts/history.php',
    '/api/v1/agent/payouts/history' => 'agent/payouts/history.php',

    '/agent/reports/bet-list' => 'agent/reports/bet_list.php',
    '/api/v1/agent/reports/bet-list' => 'agent/reports/bet_list.php',
    '/agent/reports/pl-agent' => 'agent/reports/pl_agent.php',
    '/api/v1/agent/reports/pl-agent' => 'agent/reports/pl_agent.php',
    '/agent/reports/pl-event' => 'agent/reports/pl_event.php',
    '/api/v1/agent/reports/pl-event' => 'agent/reports/pl_event.php',
    '/agent/reports/pl-market' => 'agent/reports/pl_market.php',
    '/api/v1/agent/reports/pl-market' => 'agent/reports/pl_market.php',
    '/agent/reports/real-revenue' => 'agent/reports/real_revenue.php',
    '/api/v1/agent/reports/real-revenue' => 'agent/reports/real_revenue.php',
    '/agent/reports/settlement' => 'agent/reports/settlement.php',
    '/api/v1/agent/reports/settlement' => 'agent/reports/settlement.php',
    '/agent/reports/transactions' => 'agent/reports/transactions.php',
    '/api/v1/agent/reports/transactions' => 'agent/reports/transactions.php',
    '/agent/reports/transfer-statement' => 'agent/reports/transfer_statement.php',
    '/api/v1/agent/reports/transfer-statement' => 'agent/reports/transfer_statement.php',
    '/agent/reports/exposure' => 'agent/reports/exposure.php',
    '/api/v1/agent/reports/exposure' => 'agent/reports/exposure.php',
    '/agent/reports/pnl' => 'agent/reports/pnl.php',
    '/api/v1/agent/reports/pnl' => 'agent/reports/pnl.php',
    '/agent/analysis/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/api/v1/agent/analysis/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/agent/sport-analysis' => 'agent/analysis/sport_analysis.php',
    '/api/v1/agent/sport-analysis' => 'agent/analysis/sport_analysis.php',

    // ==========================================
    // AFFILIATE CONSOLE & PORTAL API ROUTES
    // ==========================================
    '/affiliate/auth/login' => 'affiliate/auth/login.php',
    '/api/v1/affiliate/auth/login' => 'affiliate/auth/login.php',
    '/affiliate/auth/register' => 'affiliate/auth/register.php',
    '/api/v1/affiliate/auth/register' => 'affiliate/auth/register.php',
    '/affiliate/auth/status' => 'affiliate/auth/status.php',
    '/api/v1/affiliate/auth/status' => 'affiliate/auth/status.php',
    '/affiliate/auth/2fa/setup' => 'affiliate/auth/2fa/setup.php',
    '/api/v1/affiliate/auth/2fa/setup' => 'affiliate/auth/2fa/setup.php',
    '/affiliate/auth/2fa/enable' => 'affiliate/auth/2fa/enable.php',
    '/api/v1/affiliate/auth/2fa/enable' => 'affiliate/auth/2fa/enable.php',
    '/affiliate/auth/2fa/disable' => 'affiliate/auth/2fa/disable.php',
    '/api/v1/affiliate/auth/2fa/disable' => 'affiliate/auth/2fa/disable.php',
    '/affiliate/auth/2fa/verify_login' => 'affiliate/auth/2fa/verify_login.php',
    '/api/v1/affiliate/auth/2fa/verify_login' => 'affiliate/auth/2fa/verify_login.php',

    '/affiliate/dashboard' => 'affiliate/dashboard/index.php',
    '/api/v1/affiliate/dashboard' => 'affiliate/dashboard/index.php',
    '/affiliate/earnings' => 'affiliate/earnings/index.php',
    '/api/v1/affiliate/earnings' => 'affiliate/earnings/index.php',
    '/affiliate/earnings/cycle-metrics' => 'affiliate/earnings/cycle_metrics.php',
    '/api/v1/affiliate/earnings/cycle-metrics' => 'affiliate/earnings/cycle_metrics.php',
    '/affiliate/kyc' => 'affiliate/kyc/index.php',
    '/api/v1/affiliate/kyc' => 'affiliate/kyc/index.php',
    '/affiliate/kyc/upload' => 'affiliate/kyc/upload.php',
    '/api/v1/affiliate/kyc/upload' => 'affiliate/kyc/upload.php',
    '/affiliate/links' => 'affiliate/links/index.php',
    '/api/v1/affiliate/links' => 'affiliate/links/index.php',
    '/affiliate/links/track' => 'affiliate/links/track.php',
    '/api/v1/affiliate/links/track' => 'affiliate/links/track.php',
    '/affiliate/methods' => 'affiliate/methods/index.php',
    '/api/v1/affiliate/methods' => 'affiliate/methods/index.php',
    '/affiliate/network' => 'affiliate/network/index.php',
    '/api/v1/affiliate/network' => 'affiliate/network/index.php',
    '/affiliate/notifications' => 'affiliate/notifications/index.php',
    '/api/v1/affiliate/notifications' => 'affiliate/notifications/index.php',
    '/affiliate/onboarding/complete' => 'affiliate/onboarding/complete.php',
    '/api/v1/affiliate/onboarding/complete' => 'affiliate/onboarding/complete.php',
    '/affiliate/payouts/history' => 'affiliate/payouts/history.php',
    '/api/v1/affiliate/payouts/history' => 'affiliate/payouts/history.php',
    '/affiliate/payouts/request' => 'affiliate/payouts/request.php',
    '/api/v1/affiliate/payouts/request' => 'affiliate/payouts/request.php',
    '/affiliate/preferences' => 'affiliate/preferences/index.php',
    '/api/v1/affiliate/preferences' => 'affiliate/preferences/index.php',
    '/affiliate/referrals' => 'affiliate/referrals/index.php',
    '/api/v1/affiliate/referrals' => 'affiliate/referrals/index.php',
    '/affiliate/reports' => 'affiliate/reports/index.php',
    '/api/v1/affiliate/reports' => 'affiliate/reports/index.php',
    '/affiliate/reports/player-bets' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/reports/player-bets' => 'affiliate/reports/player_bets.php',
    '/affiliate/reports/player_bets' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/reports/player_bets' => 'affiliate/reports/player_bets.php',
    '/affiliate/player-activity' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/player-activity' => 'affiliate/reports/player_bets.php',
    '/affiliate/player_activity' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/player_activity' => 'affiliate/reports/player_bets.php',
    '/affiliate/reports/player-activity' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/reports/player-activity' => 'affiliate/reports/player_bets.php',
    '/affiliate/reports/player_activity' => 'affiliate/reports/player_bets.php',
    '/api/v1/affiliate/reports/player_activity' => 'affiliate/reports/player_bets.php',
    '/affiliate/settings' => 'affiliate/settings/index.php',
    '/api/v1/affiliate/settings' => 'affiliate/settings/index.php',
    '/affiliate/support' => 'affiliate/support/index.php',
    '/api/v1/affiliate/support' => 'affiliate/support/index.php'
];

?>
